### Importing libraries and path

In [28]:
import pandas as pd
import numpy as np
import os

In [29]:
path = r'C:\Users\bouas\instacart bascket analysis'

In [30]:
Deriving_New_Variables= pd.read_pickle(os.path.join(path, 'data', 'prepared_data', 'Deriving New Variables.pkl'))

In [31]:
df= Deriving_New_Variables

### Establishing the aggregation mean for the subset in order to compare it with the full df for the question 3

In [32]:
df = Deriving_New_Variables[:1000000]

In [33]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.577493
2                17.320781
3                16.084944
4                17.530458
5                14.763075
6                16.658449
7                17.031590
8                15.076662
9                15.447580
10               18.681852
11               15.467644
12               14.327957
13               16.548642
14               16.960241
15               16.121948
16               17.801107
17               15.593633
18               19.674252
19               16.899756
20               16.255442
21               25.535479

## 2/In this Exercise, you learned how to find the aggregated mean of the “order_number” column grouped by “department_id” for a subset of your dataframe. Now, repeat this process for the entire dataframe.

In [34]:
# check and preparation for the next question
df['order_number'].value_counts()

order_number
1     66241
2     64997
3     64415
4     57293
5     51452
      ...
96      438
95      425
97      420
98      387
99      357
Name: count, Length: 99, dtype: int64

In [35]:
Deriving_New_Variables.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.213779
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.171095
12               15.887671
13               16.583536
14               16.771241
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

In [36]:
# check and preparation for the next question
Deriving_New_Variables['order_number'].value_counts()

order_number
1     2076201
3     2048932
2     2046495
4     1818692
5     1626954
       ...
95      14516
96      13738
97      13356
98      12851
99      12421
Name: count, Length: 99, dtype: int64

## 3/Analyze the result. How do the results for the entire dataframe differ from those of the subset? Include your comments in a markdown cell below the executed code.

#### After comparison, the mean has changed and decreased compared to the subset of 1,000,000 rows. I think this is logical, since aggregating (meaning) more than 23 million rows differs from aggregating only 1 million rows. We also note that the order of the mean for the different departments has not changed.

## 4/Follow the instructions in the Exercise for creating a loyalty flag for existing customers using the transform() and loc() functions.

In [37]:
Deriving_New_Variables['max_order'] = Deriving_New_Variables.groupby(['user_id'])['order_number'].transform(np.max)

C:\Users\bouas\AppData\Local\Temp\ipykernel_13508\921773516.py:1: FutureWarning: The provided callable <function max at 0x000001DAD8EAF380> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  Deriving_New_Variables['max_order'] = Deriving_New_Variables.groupby(['user_id'])['order_number'].transform(np.max)

In [38]:
Deriving_New_Variables.head()

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,...,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,Busiest day,Busiest days,busiest_period_of_day,max_order
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1107,38259,prior,2,...,11,7.0,7.0,0.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,4
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,5319,196224,prior,65,...,14,1.0,3.0,1.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,99
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,7540,138499,prior,8,...,14,7.0,4.0,1.0,both,Mid-range product,Busiest day,Busiest days,Most orders,23
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,9228,79603,prior,2,...,10,30.0,2.0,0.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,5
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,9273,50005,prior,1,...,15,NaN,30.0,0.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22

In [39]:
# Ckeck if the results are true or no
user_id = 3
Deriving_New_Variables[Deriving_New_Variables['user_id'] == user_id][['user_id', 'order_number', 'max_order']]

          user_id  order_number  max_order
148395          3             2         12
494398          3            10         12
873426          3             7         12
873523          3             6         12
873580          3             4         12
...           ...           ...        ...
31220953        3             9         12
31224305        3             8         12
31629647        3             9         12
31629750        3             8         12
32393830        3             3         12

[88 rows x 3 columns]

##### processing

In [40]:

Deriving_New_Variables.loc[Deriving_New_Variables['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'
Deriving_New_Variables.loc[(Deriving_New_Variables['max_order'] <= 40) & (Deriving_New_Variables['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'
Deriving_New_Variables.loc[Deriving_New_Variables['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [41]:
# Checking results
Deriving_New_Variables[['user_id', 'loyalty_flag', 'order_number']].head(10)

   user_id      loyalty_flag  order_number
0    38259      New customer             2
1   196224    Loyal customer            65
2   138499  Regular customer             8
3    79603      New customer             2
4    50005  Regular customer             1
5   108919    Loyal customer            46
6    63782      New customer             4
7   170451      New customer             5
8   106854    Loyal customer            28
9   181127  Regular customer            10

In [42]:
#  Examining Value Counts on 'loyalty_flag'
Deriving_New_Variables['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15877395
Loyal customer      10284396
New customer         6244250
Name: count, dtype: int64

## 5/The marketing team at Instacart wants to know whether there’s a difference between the spending habits of the three types of customers you identified. Use the loyalty flag you created and check the basic statistics of the product prices for each loyalty category (Loyal Customer, Regular Customer, and New Customer)

In [43]:
Deriving_New_Variables.groupby('loyalty_flag').agg({'prices' : ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.386229  1.0  99999.0
New customer      13.294406  1.0  99999.0
Regular customer  12.495501  1.0  99999.0

#### According to basic statistics, there is no significant difference between consumers; in fact, loyal customers do not buy more expensive products, but on the contrary, they buy the cheapest ones. When their average is compared to that of other consumer categories, the difference is that they buy much more than other customers, which is why they are loyal.

## 6/Create a spending flag for each user based on the average price across all their orders

##### creating mean price colomn

In [44]:
Deriving_New_Variables['mean_price'] = Deriving_New_Variables.groupby(['user_id'])['prices'].transform(np.mean)

C:\Users\bouas\AppData\Local\Temp\ipykernel_13508\861031506.py:1: FutureWarning: The provided callable <function mean at 0x000001DAD8EAFD80> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  Deriving_New_Variables['mean_price'] = Deriving_New_Variables.groupby(['user_id'])['prices'].transform(np.mean)

##### creating spending flag colomn

In [45]:
Deriving_New_Variables.loc[Deriving_New_Variables['mean_price'] >= 10, 'spending_flag'] = 'High spender'
Deriving_New_Variables.loc[Deriving_New_Variables['mean_price'] < 10, 'spending_flag'] = 'Low spender'

##### checking results

In [46]:
Deriving_New_Variables[['user_id', 'mean_price', 'spending_flag']].head(10)

   user_id  mean_price spending_flag
0    38259    7.163333   Low spender
1   196224    5.342729   Low spender
2   138499    7.469540   Low spender
3    79603    6.986207   Low spender
4    50005    7.493154   Low spender
5   108919    7.020681   Low spender
6    63782    5.700000   Low spender
7   170451    6.534286   Low spender
8   106854    8.594301   Low spender
9   181127    7.177143   Low spender

##### second check

In [47]:
Deriving_New_Variables['spending_flag'].value_counts()

spending_flag
Low spender     31771789
High spender      634252
Name: count, dtype: int64

## 7/Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column.

##### creating median for days since last order

In [48]:
Deriving_New_Variables['median_days_since_last_orders'] = Deriving_New_Variables.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

C:\Users\bouas\AppData\Local\Temp\ipykernel_13508\735435940.py:1: FutureWarning: The provided callable <function median at 0x000001DAD8FEAE80> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  Deriving_New_Variables['median_days_since_last_orders'] = Deriving_New_Variables.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

##### creating order frequency flag

In [49]:
Deriving_New_Variables.loc[Deriving_New_Variables['median_days_since_last_orders'] > 20, 'order_frequency_flag'] = 'Non-frequent customer'
Deriving_New_Variables.loc[(Deriving_New_Variables['median_days_since_last_orders'] <= 20) & (Deriving_New_Variables['median_days_since_last_orders'] > 10), 'order_frequency_flag'] = 'Regular customer'
Deriving_New_Variables.loc[Deriving_New_Variables['median_days_since_last_orders'] <= 10, 'order_frequency_flag'] = 'Frequent customer'

##### checking result

In [50]:
Deriving_New_Variables[['user_id', 'median_days_since_last_orders', 'order_frequency_flag']].head(10)

   user_id  median_days_since_last_orders   order_frequency_flag
0    38259                           30.0  Non-frequent customer
1   196224                            1.0      Frequent customer
2   138499                            7.0      Frequent customer
3    79603                           30.0  Non-frequent customer
4    50005                            7.0      Frequent customer
5   108919                            7.0      Frequent customer
6    63782                           14.0       Regular customer
7   170451                           20.0       Regular customer
8   106854                            3.0      Frequent customer
9   181127                           14.0       Regular customer

##### second check

In [51]:
Deriving_New_Variables['order_frequency_flag'].value_counts()

order_frequency_flag
Frequent customer        21560324
Regular customer          7209005
Non-frequent customer     3636707
Name: count, dtype: int64

In [54]:
Deriving_New_Variables.columns

Index(['Unnamed: 0', 'product_id', 'product_name', 'aisle_id', 'department_id',
       'prices', 'order_id', 'user_id', 'eval_set', 'order_number',
       'order_dow', 'order_hour_of_day', 'days_since_prior_order',
       'add_to_cart_order', 'reordered', '_merge', 'price_range_loc',
       'Busiest day', 'Busiest days', 'busiest_period_of_day', 'max_order',
       'loyalty_flag', 'mean_price', 'spending_flag',
       'median_days_since_last_orders', 'order_frequency_flag'],
      dtype='object')

### Exporting file

In [52]:
Deriving_New_Variables.loc[Deriving_New_Variables['prices'] >100, 'prices'] = np.nan

In [53]:
# Exporting the df
Deriving_New_Variables.to_pickle(os.path.join(path, 'data', 'prepared_data', 'grouping_data_order_product.pkl'))