In [76]:

import pandas as pd
import numpy as np
import os

In [77]:
path = r'C:\Users\bouas\instacart bascket analysis'

In [78]:
Deriving_New_Variables= pd.read_pickle(os.path.join(path, 'data', 'prepared_data', 'Deriving New Variables.pkl'))

In [79]:
df= Deriving_New_Variables

In [80]:
df = Deriving_New_Variables[:1000000]

In [81]:
df.shape

(1000000, 20)

In [82]:
df.groupby('product_name')

In [83]:
df.head()

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,Busiest day,Busiest days,busiest_period_of_day
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1107,38259,prior,2,1,11,7.0,7.0,0.0,both,Mid-range product,Regularly busy,Busiest days,Most orders
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,5319,196224,prior,65,1,14,1.0,3.0,1.0,both,Mid-range product,Regularly busy,Busiest days,Most orders
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,7540,138499,prior,8,0,14,7.0,4.0,1.0,both,Mid-range product,Busiest day,Busiest days,Most orders
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,9228,79603,prior,2,2,10,30.0,2.0,0.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,9273,50005,prior,1,1,15,NaN,30.0,0.0,both,Mid-range product,Regularly busy,Busiest days,Most orders

In [84]:
# If order_number is a column in a DataFrame df
df['order_number'].value_counts()

order_number
1     66241
2     64997
3     64415
4     57293
5     51452
      ...
96      438
95      425
97      420
98      387
99      357
Name: count, Length: 99, dtype: int64

In [85]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.577493
2                17.320781
3                16.084944
4                17.530458
5                14.763075
6                16.658449
7                17.031590
8                15.076662
9                15.447580
10               18.681852
11               15.467644
12               14.327957
13               16.548642
14               16.960241
15               16.121948
16               17.801107
17               15.593633
18               19.674252
19               16.899756
20               16.255442
21               25.535479

In [86]:
df.groupby('department_id')['order_number'].mean()

department_id
1     15.577493
2     17.320781
3     16.084944
4     17.530458
5     14.763075
6     16.658449
7     17.031590
8     15.076662
9     15.447580
10    18.681852
11    15.467644
12    14.327957
13    16.548642
14    16.960241
15    16.121948
16    17.801107
17    15.593633
18    19.674252
19    16.899756
20    16.255442
21    25.535479
Name: order_number, dtype: float64

In [87]:
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                15.577493   1  99
2                17.320781   1  96
3                16.084944   1  99
4                17.530458   1  99
5                14.763075   1  99
6                16.658449   1  99
7                17.031590   1  99
8                15.076662   1  98
9                15.447580   1  99
10               18.681852   1  99
11               15.467644   1  99
12               14.327957   1  99
13               16.548642   1  99
14               16.960241   1  99
15               16.121948   1  99
16               17.801107   1  99
17               15.593633   1  99
18               19.674252   1  99
19               16.899756   1  99
20               16.255442   1  99
21               25.535479   1  98

In [88]:
Deriving_New_Variables['max_order'] = Deriving_New_Variables.groupby(['user_id'])['order_number'].transform(np.max)

C:\Users\bouas\AppData\Local\Temp\ipykernel_78748\921773516.py:1: FutureWarning: The provided callable <function max at 0x000002A5129CF100> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  Deriving_New_Variables['max_order'] = Deriving_New_Variables.groupby(['user_id'])['order_number'].transform(np.max)

In [89]:
Deriving_New_Variables.head()

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,...,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,Busiest day,Busiest days,busiest_period_of_day,max_order
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1107,38259,prior,2,...,11,7.0,7.0,0.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,4
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,5319,196224,prior,65,...,14,1.0,3.0,1.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,99
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,7540,138499,prior,8,...,14,7.0,4.0,1.0,both,Mid-range product,Busiest day,Busiest days,Most orders,23
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,9228,79603,prior,2,...,10,30.0,2.0,0.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,5
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,9273,50005,prior,1,...,15,NaN,30.0,0.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22

In [90]:
user_id = 1
Deriving_New_Variables[Deriving_New_Variables['user_id'] == user_id][['user_id', 'order_number', 'max_order']]

          user_id  order_number  max_order
96915           1             5         10
97411           1             3         10
98186           1             7         10
115917          1             4         10
116323          1             9         10
117387          1             2         10
118800          1             1         10
118930          1            10         10
124876          1             8         10
127601          1             6         10
5972029         1             5         10
5972051         1             3         10
5972102         1             7         10
5973035         1             4         10
5973051         1             9         10
5973109         1             2         10
5973193         1            10         10
5973533         1             8         10
5973677         1             6         10
6003496         1             5         10
7158144         1             5         10
7158226         1             3         10
7158369         1             7         10
7161558         1             4         10
7161625         1             9         10
7161797         1             2         10
7162029         1             1         10
7162048         1            10         10
7163127         1             8         10
7163613         1             6         10
7453817         1             7         10
7455852         1             2         10
7456022         1            10         10
7566819         1             5         10
7784973         1             2         10
8446946         1             1         10
10078638        1             5         10
16105986        1             5         10
16106069        1             3         10
16106195        1             7         10
16109271        1             4         10
16109347        1             9         10
16109800        1            10         10
16110840        1             8         10
16111312        1             6         10
16643946        1             2         10
16644031        1             1         10
17010260        1             4         10
17010364        1             1         10
19833988        1             3         10
23272461        1            10         10
24932916        1            10         10
25458044        1            10         10
26751857        1             5         10
29719520        1             9         10
29720170        1            10         10
29721613        1             8         10
32086331        1             9         10
32104502        1             8         10

In [91]:
Deriving_New_Variables.loc[Deriving_New_Variables['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'
Deriving_New_Variables.loc[(Deriving_New_Variables['max_order'] <= 40) & (Deriving_New_Variables['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'
Deriving_New_Variables.loc[Deriving_New_Variables['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [92]:
Deriving_New_Variables.head()

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,...,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,Busiest day,Busiest days,busiest_period_of_day,max_order,loyalty_flag
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1107,38259,prior,2,...,7.0,7.0,0.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,4,New customer
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,5319,196224,prior,65,...,1.0,3.0,1.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,99,Loyal customer
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,7540,138499,prior,8,...,7.0,4.0,1.0,both,Mid-range product,Busiest day,Busiest days,Most orders,23,Regular customer
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,9228,79603,prior,2,...,30.0,2.0,0.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,5,New customer
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,9273,50005,prior,1,...,NaN,30.0,0.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer

In [93]:
Deriving_New_Variables['loyalty_flag'].value_counts()

loyalty_flag
Regular customer    15877395
Loyal customer      10284396
New customer         6244250
Name: count, dtype: int64

In [94]:
Deriving_New_Variables[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0     38259      New customer             2
1    196224    Loyal customer            65
2    138499  Regular customer             8
3     79603      New customer             2
4     50005  Regular customer             1
5    108919    Loyal customer            46
6     63782      New customer             4
7    170451      New customer             5
8    106854    Loyal customer            28
9    181127  Regular customer            10
10   106519  Regular customer            18
11   145505    Loyal customer            64
12   139923  Regular customer            16
13   110984  Regular customer             2
14   180719    Loyal customer            84
15   142388  Regular customer             7
16   200356  Regular customer            11
17     4122  Regular customer            11
18   162394      New customer             2
19   148255  Regular customer            18
20   205157  Regular customer            11
21   181127  Regular customer             3
22    92648  Regular customer             8
23    30345      New customer             6
24    50898  Regular customer            28
25    57996    Loyal customer            12
26    77956    Loyal customer            90
27    22561      New customer             4
28   199115  Regular customer            20
29    91160    Loyal customer            32
30    50150  Regular customer            17
31    38748  Regular customer            16
32    65777    Loyal customer            47
33   134728  Regular customer            18
34    11119  Regular customer            18
35    45784  Regular customer             4
36    21054      New customer             3
37   196224    Loyal customer            23
38   102960    Loyal customer            21
39   113429  Regular customer            17
40   111982    Loyal customer            76
41   144159  Regular customer             3
42    72224    Loyal customer            12
43    23234  Regular customer            10
44   131925  Regular customer             8
45    16057  Regular customer             2
46   124716      New customer             5
47    60380  Regular customer            26
48   197324  Regular customer            12
49   157800  Regular customer             9
50    48228      New customer             1
51    23513  Regular customer             5
52    95847    Loyal customer            44
53   101727  Regular customer            28
54   139923  Regular customer            19
55    11448  Regular customer            20
56   162795  Regular customer             6
57   134130  Regular customer            13
58   178504  Regular customer             8
59    80421      New customer             8